<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>YqlossClientHarmony</RootNamespace>
        <AssemblyName>YqlossClientHarmony</AssemblyName>
        <LangVersion>13</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <EnableDefaultItems>false</EnableDefaultItems>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GameManagedPath>ADOFAIGame\A Dance of Fire and Ice\A Dance of Fire and Ice_Data\Managed</GameManagedPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="$(GameManagedPath)\**\*.dll">
            <HintPath>%(FullPath)</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="**\*.cs"
                 Exclude="ADOFAIGame\**\*.cs;bin\**\*.cs;obj\**\*.cs"/>
        <Content Include="Languages\**\*.lang;*.md"/>
    </ItemGroup>
</Project>
